name: Deploy FastAPI to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:              # <-- steps is a list
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to VM        # <-- this - name: is valid because itâ€™s inside steps
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 34.19.77.229
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          timeout: 30s
          command_timeout: 10m
          proxy_port: 22
          proxy_timeout: 30s
          script: |
            mkdir -p ~/fastapi-demo-app
            cd ~/fastapi-demo-app || exit 1

            if [ ! -d ".git" ]; then
              git init
              git remote add origin https://github.com/felixxavierdhasd/fastapi-gcp-ci-cd.git
            else
              git remote set-url origin https://github.com/felixxavierdhasd/fastapi-gcp-ci-cd.git
            fi
            
            git fetch origin
            git reset --hard origin/main

            if [ ! -d "venv" ]; then
              python3 -m venv venv || exit 1
            fi
            source venv/bin/activate || exit 1

            pip install --upgrade pip
            pip install -r requirements.txt || exit 1

            pkill -f uvicorn || true

            nohup venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &
